sudo: false
language: clojure
env:
  global:
  - DATABASE_URL='jdbc:postgresql://localhost/travis_ci_test?user=postgres'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
branches: 
  only:
  - master